### ISSUE TITLE
Typescript error with namespace `spdxExpressionParse`  import on version 2.0.0

### ISSUE THREAD

**Issue by tdraper-dev** [CycloneDX/cyclonedx-javascript-library#768] opened 2023-05-18 18:37 UTC
Running Typecheck, getting the following error:

```
node_modules/@cyclonedx/cyclonedx-library/src/spdx.ts:56:5 - error TS2349: This expression is not callable.
  Type '{ default: (source: string) => Info; }' has no call signatures.

56     spdxExpressionParse(value)
       ~~~~~~~~~~~~~~~~~~~

  node_modules/@cyclonedx/cyclonedx-library/src/spdx.ts:20:1
    20 import * as spdxExpressionParse from 'spdx-expression-parse'
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.


Found 1 error in node_modules/@cyclonedx/cyclonedx-library/src/spdx.ts:56
```

**Comment by tdraper-dev** [comment] 2023-05-18 18:39
Maybe try changing the import at `line 20` to
```
import spdxExpressionParse from 'spdx-expression-parse`
```

**Comment by tdraper-dev** [comment] 2023-05-18 18:48
The patch that fixes this for me:

```
diff --git a/node_modules/@cyclonedx/cyclonedx-library/src/spdx.ts b/node_modules/@cyclonedx/cyclonedx-library/src/spdx.ts
index dfd210e..772d32b 100644
--- a/node_modules/@cyclonedx/cyclonedx-library/src/spdx.ts
+++ b/node_modules/@cyclonedx/cyclonedx-library/src/spdx.ts
@@ -17,7 +17,7 @@ SPDX-License-Identifier: Apache-2.0
 Copyright (c) OWASP Foundation. All Rights Reserved.
 */
 
-import * as spdxExpressionParse from 'spdx-expression-parse'
+import spdxExpressionParse from 'spdx-expression-parse'
 
 /* @ts-expect-error: TS6059 -- this works as long as the file/path is available in dist-package. */
 import { enum as _spdxSpecEnum } from '../res/schema/spdx.SNAPSHOT.schema.json' assert { type: 'json' }
diff --git a/node_modules/@cyclonedx/cyclonedx-library/tsconfig.json b/node_modules/@cyclonedx/cyclonedx-library/tsconfig.json
index 3c48e6b..2a8e459 100644
--- a/node_modules/@cyclonedx/cyclonedx-library/tsconfig.json
+++ b/node_modules/@cyclonedx/cyclonedx-library/tsconfig.json
@@ -72,7 +72,7 @@
     /* Interop Constraints */
     "isolatedModules": true,                          /* Ensure that each file can be safely transpiled without relying on other imports. */
     // "allowSyntheticDefaultImports": true,             /* Allow 'import x from y' when a module doesn't have a default export. */
-    // "esModuleInterop": true,                          /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */
+    "esModuleInterop": true,                          /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */
     // "preserveSymlinks": true,                         /* Disable resolving symlinks to their realpath. This correlates to the same flag in node. */
     "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */
```

**Comment by jkowalleck** [comment] 2023-05-19 07:55
> Running Typecheck, getting the following error:

@tdraper-dev could you give more context? maybe a reproducible example?

**Comment by jkowalleck** [comment] 2023-06-03 13:20
@tdraper-dev is it possible that you have tour type checker in your own project configured wrong? 
you wrote: 
> `node_modules/@cyclonedx/cyclonedx-library/src/spdx.ts:56:5 - error TS2349: This expression is not callable.` [...]
it appears that you are type ckecking files inside your `node_modules` folder. Files in there are vendored.

`@cyclonedx/cyclonedx-library`'s type descriptions are not in the source folder, but in the `dist.d` folder - as advertised in the `package.json`:
* https://github.com/CycloneDX/cyclonedx-javascript-library/blob/main/package.json#L101
* https://github.com/CycloneDX/cyclonedx-javascript-library/blob/main/package.json#L104

You, instead, are scanning the shipped source folder, which is not even advertised.

if you intended to type check `@cyclonedx/cyclonedx-library`'s shipped `src` folder, then you should honor `@cyclonedx/cyclonedx-library`'s shipped build instruction/config files,too.

**Comment by jkowalleck** [comment] 2023-06-03 13:21
will close this. not locked.
false alarm.

furthermore, the proposed improvements would break the project as a whole. (run the tests!)

**Closed by jkowalleck** 2023-06-03 13:21 UTC
