### ISSUE TITLE
Duplicate identifier

### ISSUE THREAD

**Issue by davidkarlsen** [CycloneDX/cyclonedx-javascript-library#130] opened 2022-07-26 10:10 UTC
See https://github.com/evryfs/sbom-dependency-submission-action/runs/7497968551?check_suite_focus=true - there seems to be a snag with the 1.0.1 release compared to 1.0.0

**Comment by jkowalleck** [comment] 2022-07-26 16:03
what i am seeing: 
```text
> typescript-action@0.0.0 build
> tsc

node_modules/@cyclonedx/cyclonedx-library/node_modules/packageurl-js/src/package-url.d.ts(31,9): error TS2300: Duplicate identifier 'PackageURL'.
node_modules/packageurl-js/src/package-url.d.ts(31,9): error TS2300: Duplicate identifier 'PackageURL'.
Error: Process completed with exit code 2.
```

My thoughts: 
Why is there a folder `node_modules/@cyclonedx/cyclonedx-library/node_modules`?  see https://github.com/evryfs/sbom-dependency-submission-action/pull/40#discussion_r930127728
Reason: this is caused by conflicting dependencies on `packageurl-js` in https://github.com/evryfs/sbom-dependency-submission-action/blob/dependabot/npm_and_yarn/cyclonedx/cyclonedx-library-1.0.1/package-lock.json

searched for `packageurl-js` and find 
* see  https://github.com/evryfs/sbom-dependency-submission-action/blob/dependabot/npm_and_yarn/cyclonedx/cyclonedx-library-1.0.1/package-lock.json#L685
* see  https://github.com/evryfs/sbom-dependency-submission-action/blob/dependabot/npm_and_yarn/cyclonedx/cyclonedx-library-1.0.1/package-lock.json#L729

one is requireing ``packageurl-js: ^0.0.7` (meaning range from `>= 0.0.7` to `< 0.0.8`)
the other one is requiring `packageurl-js: 0.0.6` (fixed)

npm resolves the conflict by putting the requrements to their needs.
and then the TypeScript compiler _you_ configured crashes for a reason ... 

Solution i see: have the fixed dependency to `packageurl-js` solved  in `@github/dependency-submission-toolkit`
Best: have the maintainers of `packageurl-js` switch to a proper versioning.

In the meantime i will provide a version of `@cyclonedx/cyclonedx-library` which  downgrades  `packageurl-js: ^0.0.6`  
which again is compatible  with  `packageurl-js: 0.0.6` 
so your issues should be fixed

**Comment by jkowalleck** [comment] 2022-07-26 16:24
thanks for the report,

@davidkarlsen 

WIll release a bugfix soon.

**Closed** 2022-07-26 16:29 UTC
Labels: enhancement

**Comment by davidkarlsen** [comment] 2022-07-26 18:32
Great - new version worked well. Thanks a lot
